name: senior-design-env
dependencies:
  - python=3.7.4
  - numpy=1.18.1
  - seaborn=0.9.0
  - pandas=1.0.0
  - mysql-connector-python=8.0.18
  - pymongo=3.9.0
  - faker=4.0.0
  - fuzzywuzzy=0.17.0
  - pymc3=3.8
channels:
  - defaults
  - conda-forge
